title = "SimCLR-S2"
baseURL = "https://mids-irrigation-capstone.github.io"
languageCode = "en-us"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""

[params]
  favicon = ""
  # site_logo = "/images/logo.png"
  description = "W210 Capstone Project - UC Berkeley"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/MIDS-Irrigation-Capstone/Spring2021"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/crop.jpg"
  cover_dimming_class="bg-black-10"
  recent_posts_number = 10
  custom_css = ["/css/main.css"]
  mainSections = ["data", "models", "results"]
