title = "Self-supervised Learning for Irrigation Detection"
baseURL = ""
languageCode = "en-us"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""

[params]
  favicon = ""
  site_logo = "/images/logo.png"
  description = "W210 Capstone Project - UC Berkeley"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/MIDS-Irrigation-Capstone/Spring2021"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/crop.jpg"
  cover_dimming_class="bg-black-10"
  recent_posts_number = 3
  custom_css = ["css/main.css"]
  mainSections = ["models", "results"]


